config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # # INDEX
  get '/tasks', to: 'tasks#index', as: :index
  # # SHOW
  get '/tasks/:id', to: 'tasks#show', as: :show
  # # NEW
  get '/tasks/new', to: 'tasks#new'
  # # CREATE
  post '/tasks', to: 'tasks#create'
  # # EDIT
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit
  post '/tasks/:id/done', to: 'tasks#done'
  # # UPDATE
  put 'tasks/:id', to: 'tasks#update'
  # # DELETE
  delete '/tasks/:id', to: 'tasks#destroy', as: :delete

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
  @tasks = Task.all
  @task = Task.new

  end

  def show          # GET /restaurants/:id
  @task = Task.find(params[:id])
  end

  def new           # GET /restaurants/new
  @task = Task.new
  end

  def create        # POST /restaurants
    task = Task.new
    task.title = params[:task][:title]
    task.details = params[:task][:details]
    task.completed = params[:task][:completed]
    task.save!

    if task.save
      redirect_to tasks_path
    else
      render:now
    end

  end

  def edit
    @task = Task.find(params[:id])
    @task = Task.new
  end

  def done
    @task = Task.find(params[:id])
  end

  def update
    if @task.update(task_params)
      redirect_to index_path
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to index_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |task_form| %>
  <%= task_form.label :title %>
  <%= task_form.text_field :title %>

  <%= task_form.label :details %>
  <%= task_form.text_field :details %>

  <%= task_form.label :completed %>
  <%= task_form.text_field :completed %>

  <%= task_form.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks index</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= task.title %>
      <%= link_to "view the details of a task", show_path(task) %>
      <%= link_to "Edit", edit_path(id: task.id) %>
      <%= link_to "Delete", delete_path(id: task.id),
        method: :delete,
        data: { confirm: "Are you sure you want to delete it?" } %>
    </li>
  <% end %>
</ul>

<%= render 'form' %>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>

<p>Details: <%= @task.details %></p>
<p>Completed: <%= @task.completed %></p>